export const DEFAULT_NAME = 'Umi Max';

export const FACTOR_QUOTAS = [
  "long_ic_3",
  "long_ic_10",
  "long_ic_21",
  "long_ic_63",
  "long_ret_3",
  "short_ic_3",
  "instruments",
  "long_ic_126",
  "long_ic_252",
  "long_ret_10",
  "long_ret_21",
  "long_ret_63",
  "short_ic_10",
  "short_ic_21",
  "short_ic_63",
  "short_ret_3",
  "factor_field",
  "long_ret_126",
  "long_ret_252",
  "short_ic_126",
  "short_ic_252",
  "short_ret_10",
  "short_ret_21",
  "short_ret_63",
  "long_short_ic",
  "long_short_ir",
  "long_turnover",
  "short_ret_126",
  "short_ret_252",
  "long_portfolio",
  "short_turnover",
  "long_short_ic_3",
  "short_portfolio",
  "factor_direction",
  "long_sharp_ratio",
  "long_short_ic_10",
  "long_short_ic_21",
  "long_short_ic_63",
  "long_short_ret_3",
  "long_win_percent",
  "long_max_drawdown",
  "long_return_ratio",
  "long_short_ic_126",
  "long_short_ic_252",
  "long_short_ret_10",
  "long_short_ret_21",
  "long_short_ret_63",
  "long_trading_days",
  "short_sharp_ratio",
  "short_win_percent",
  "long_short_ret_126",
  "long_short_ret_252",
  "short_max_drawdown",
  "short_return_ratio",
  "short_trading_days",
  "long_short_turnover",
  "long_ex_return_ratio",
  "long_short_portfolio",
  "short_ex_return_ratio",
  "long_information_ratio",
  "long_return_volatility",
  "long_short_sharp_ratio",
  "long_short_win_percent",
  "long_short_max_drawdown",
  "long_short_return_ratio",
  "long_short_trading_days",
  "short_information_ratio",
  "short_return_volatility",
  "long_annual_return_ratio",
  "short_annual_return_ratio",
  "long_short_ex_return_ratio",
  "long_ex_annual_return_ratio",
  "long_short_information_ratio",
  "long_short_return_volatility",
  "short_ex_annual_return_ratio",
  "long_short_annual_return_ratio"
]

export const OPERATORS = [
  {
    label: '大于',
    value: 'gt',
  },
  {
    label: '等于',
    value: 'equal',
  },
  {
    label: '小于',
    value: 'lt',
  },
  {
    label: '大于等于',
    value: 'gte',
  },
  {
    label: '小于等于',
    value: 'lte',
  },
  {
    label: '不等于',
    value: 'not',
  }
]